--credits to Blizzard, to Wowpedia and WoWWiki for some of the texts. Licence CC BY-SA 3.0.
locale = GetLocale();
initialized = false;
text = {};

function Lorehelper_Text(key)
	if Lorehelper_VarFrame == nil then
		print ("Lorehelper: can't create a text when addon variables aren't loaded");
		return nil;
	end
	
	if initialized == false then
		Lorehelper_Text_Initialize()
	end

	if text[key] ~= nil then
		return text[key];
	else
		return key;
	end
end

function Lorehelper_Text_Initialize()
	--if locale:sub(1, 2) == "de" then
		--Lorehelper_Text_Initialize_German();
	--else
		Lorehelper_Text_Initialize_English();
	--end
	initialized = true;
end

function Lorehelper_Text_Initialize_English()
	------------------------------------------------------------	
	------------------------------------------------------------
	------------------------------------------------------------
	text["DwarfStandardAvoided"]="Ye were not much affected by these events."
	text["DwarfStandardLostSomeone"]="Ye have lost someone you loved during these events."
	text["DwarfStandardParticipated"]="Ye did fight in this war. Luckily, survived."
	text["DwarfStandardLostEverything"]="Ye have suffered a lot during these horrible events. The scars of this war will forever remind ye of those ye loved and lost, of burnt houses, of crying gnomes, of fresh graves..."

	text["DwarfZoneAvoided"]=""
	text["DwarfZoneLost someone"]="This is where someone ye loved perished."
	text["DwarfZoneParticipated"]="Ye've been fighting here. Looks peaceful now, but is it for long?"
	text["DwarfZoneLost everything"]="This is where ye suffered a terrible loss..."

	text["DwarfZoneWestern Plaguelands"]="All the way from here to the east are the lands haunted by the undead Scourge. To the west, in Tirisfal Glades, the undead of Horde reside.|n|nBefore the plague, these were human lands of Lordaeron. But then the people of the area have been decimated by the undead. Most of the survivors fled, some have joined the Scarlet Crusade - the order devoted to exterminating the undead. Their fanatism might have caused just as many human deaths as the ruthlessness of the Scourge..."
	text["DwarfZoneTooltipWestern Plaguelands"]="A human paladin is rumored to live in an exile far to|nthe north, on the shores of the Thondroril River."
	text["DwarfZoneBadlands"]="Despite its position between Stormwind and Dun Morogh, the Badlands have been Horde territory, so to say, \"traditionally\" - since Horde invaded Azeroth anyway. For us, the important place in this land is Uldaman.|n|nIt was partially excavated by the explorers from Ironforge prior to Third War, but has since fallen into the hands of the troggs and Dark Irons. These brutes use this ancient place, that may hold secrets of universal importance, as a mere mine!"
	text["DwarfZoneClanBronzebeard"]="Ironforge's entire population is eager to see what's down there. Maybe one day ye will honor yer clan by helping to crush the intruders and unlock the mysteries of our ancient past."
	text["DwarfZoneTooltipBadlands"]="Uldaman is a mistery that many try to uncover - both|nin the libraries of Ironforge and here in Badlands, in the field."
	text["DwarfZoneWetlands"]="The Wetlands have been the site of many battles through the times.|n|nAfter the first round of War of the Three Hammers, Grim Batol was founded here by Wildhammers. Later, Dark Irons invaded the town. They were driven back, but not before leaving a curse on the fortress, making it uninhabitable.|n|nDuring Second War, the orcs took Grim Batol for a time. Later on though, they were subject to the wrath of the red dragonflight who, when freed of their enslavement from the orcs, destroyed their bases, killing orcs en masse. The surviving orcs fled south to the mountains, where they live to this day."

	--non-standard key format!	
	text["DwarfZoneWetlandsClanWildhammer"]="If not for Dark Irons, Wildhammers might have still called this land ye home."

	text["DwarfZoneSearing Gorge"]="One of the fiercest battles of Second War took place here, the Siege of Blackrock Spire. After their defeat in the siege, Horde was an easy prey.|n|nUnfortunately, remnants of the old Horde still dominate Burning Steppes to the south of the Mountain.|n|nAnd Dark Irons dominate the Searing Gorge. The only base where we won't be killed on sight is Thorium Point. Thorium Brotherhood, a group of Dark Irons who no longer belong to the clan, resides there."
	text["DwarfZoneTooltipSearing Gorge"]="A gigantic beast known as Margol the Rager|nroams near its cave in the southeastern region|nof Searing Gorge."
	text["DwarfZoneClanDark Iron"]="Ye were one of them maybe? Or did ye escape the Blackrock Mountain together with them? In any case, probably one day ye will earn their respect."
	text["DwarfZoneThe Hinterlands"]="Our Wildhammer friends live here. Formally, Wildhammers are not a part of the reformed after Third War Alliance, but they do cooperate with us.|n|nWildhammers created their own small alliance - with the high elves of Quel'Danil, much to the ire of their common enemy, the Revantusk trolls. These trolls are in similar relations with Horde - declined to rejoin it, but did agree to a pact of friendship and mutual assistance.|n|nYe see - so far from the big cities, but the politics is just as messy as in a capital!"

	--non-standard key format!
	text["DwarfZoneThe HinterlandsClanWildhammer"]="Aerie Peak is yer home. Yer a free adventurer now, but perhaps you stop here for some time to help yer home clan with their daily struggles."

	--	text["DwarfZoneBlasted Lands"]="This is the area where the orcish Horde first entered Azeroth through the Dark Portal, followed soon by their attack on the human lands to the northwest, and, ultimately, by their victory in First War."
	text["DwarfZoneRedridge Mountains"]="This seemingly-idyllic part of human Stormwind Kingdom was one of the important battlefields of First War. Eventually conquered by the orcish Horde, it has only returned to the Alliance a few years later.|n|nEven now, \"Dark Horde\", remnants of the old Horde, controls the Burning Steppes to the north and plagues Redridge with constant attacks."
	text["DwarfZoneAshenvale"]="Forests of Ashenvale is where the Alliance has first met the night elves. The contact was not a peaceful one... But later, understanding that demons of Burning Legion are a greater evil, night elves have joined forces with Alliance and Horde to repel the demonic invasion."
	------------------------------------------------------------
	text["DwarfAgeYoung"]="\"Four years have passed since the mortal races banded together and stood united against the might of the Burning Legion\".|n|nYer childhood was quite peaceful, but during yer teenage years the world was shackled by the demonic invasion - Third War they call it. Perhaps the stories of the Hijal veterans have made ye hungry for heroic deeds, or maybe the horrors of the war have influenced yer decision to become an independent adventurer.|n|nIn any case, yer an adult now, and yer future is in your hands..."	
	text["DwarfAgeThirdWar"]="\"Four years have passed since the mortal races banded together and stood united against the might of the Burning Legion\".|n|nYe were an adult when these events, known as Third War, took place.|n|nSome might have said before that the orcs are the greatest enemy the Alliance have ever faced, but we now know that there are greater horrors."	
	text["DwarfAgePeace"]="Ye were lucky enough to have a relatively peaceful youth. After Bronzebeard and Wildhammer dwarves have joined the Alliance, orc invaders didn't stood a chance! Only a few years ago the world have faced the wrath of their former masters - demons of the Burning Legion.|n|nYe know that the eternal peace is impossible, but ye have at least felt the taste it."
	text["DwarfAgeSecondWar"]="By the time Bronzebeard and Wildhammer dwarves have joined the Alliance to oppose the bloodthirsty Horde, ye had grown up already.|n|nThe Second War was the great victory of yer time. A decade of relative peace followed, and only a few years ago the world have faced the wrath of demons of the Burning Legion, former masters of orcs.|n|nYe know that even if an enemy is defeated, there is a chance that a greater foe lurks in shadows, only waiting for the proper moment to attack..."
	text["DwarfAgeWarofThreeHammers"]="Yer not some youngling I see! Ye remember a different world - no orcs, no Kalimdor too.|n|nBronzebeard and Wildhammer dwarves lived in peace for centuries, but there was a time when we were fighting. It is called War of Three Hammers because of Dark Irons, but Dark Irons are always the same - power-hungry and fight civilized dwarves. Could've as well called it War of Two Hammers if ye ask me.|n|nBut we probably should not question how it's been called AT YER TIME, right, granny? Hehe, don't ye take offense... Let us have another ale and be friends again."
	------------------------------------------------------------
	text["DwarfClan"]="Yer in the lands of Bronzebeard dwarves, " ..Lorehelper_VarFrame.name.. ", but are ye one of the Bronzebeards?|n|nThe three mighty clans have shared the city of Ironforge some 250 years ago. Now Wildhammers live on the peaks of Hinterlands, and Dark Irons reside deep below the Blackrock Mountain.|n|nWhat is your clan of birth?"
	text["DwarfClanBronzebeard"]="So yer one of us.|n|nWe are the only clan living in the great city of Ironforge. It has been like this for centuries, since War of the Three Hammers.|n|nAfter the conflict was over, Wildhammers were invited back into Ironforge, but they were too proud to accept the offer. Most of them reside in the city of Aerie Peak in the Hinterlands.|n|nAnd Dark Irons could never become part of the family again. Most of them serve Ragnaros the Firelord since the War. Needless to say, Dark Irons are mortal enemies of both Bronzebeards and Wildhammers - but mostly Bronzebeards since their Blackrock Mountain is so damn close..."
	text["DwarfClanWildhammer"]="So yer one of our Wildhammer allies.|n|nDuring the civil war, Wildhammers were banished from Ironforge. They founded their own kingdom within the distant peak of Grim Batol.|n|nAfter some years, Dark Irons tried to strike back at both clans. Though slain in battle for Grim Batol, Dark Iron empress Modgud had left an evil stain on the city, and the Wildhammers found it uninhabitable.|n|nWildhammers, now friends of Bronzebeards again, were invited back into Ironforge, but were too proud to accept the offer. They ventured north, settling in the lush forests of the Hinterlands. There, the Wildhammers grew closer to nature and even bonded with the mighty gryphons of the area."
	text["DwarfClanDarkIron"]="Don't ye try anything funny here, Dark Iron!|n|nDuring the civil war, Dark Irons were banished from Ironforge. After some years, they tried to strike back at the two other clans. But Wildhammers were victorious again, and so were Bronzebeards.|n|nDark Irons have retreated back to the Redridge Mountains... And would live there to this day if they were not so keen on destroying what all civilized dwarves cherish!|n|nI am sorry, perhaps its not yet fault. Anyway, that part of Redridge is no more, and most of the Dark Irons live under the volcano known as Blackrock Mountain. Many of them are rumored to serve Ragnaros the Firelord, the being resposible for burning that whole area to ashes.|n|nI am sure you enjoy cozy snow of Dun Morogh way more than the underground prison of an Elemental Lord!"
	------------------------------------------------------------	
	text["DwarfEventWarofThreeHammers"]="Death of High King Modimus Anvilmar marked the beginning of War of the Three Hammers. Bronzebeards, Wildhammers, and Dark Irons have been fighting to control the Ironforge.|n|nSecond part of this conflict was a war started by Dark Irons, who attacked the two other clans.|n|nAftermath of the War are pretty obvious to anyone who have seen the surroundings of the Blackrock Mountain. This is what Dark Irons have done with their homeland in a desperate attempt to revenge the two other clans."
	text["DwarfEventWarofThreeHammersBronzebeard"]="During the civil war, we banished the Dark Irons and Wildhammers from Ironforge. Maybe not much to be proud of, but this is how it was.|n|nAfter some years, Dark Irons tried to strike back at both clans. But Bronzebeards were victorious again, and so were Wildhammers.|n|nThis war have taught the two clans something. In the Valley of Kings in Loch Modan, there is a monument to Bronzebeard and Wildhammer friendship, and while rivalries would continue, we did not raise arms against one another ever again.|n|nCan't say the same about Dark Irons unfortunately..."
	text["DwarfEventWarofThreeHammersWildhammer"]="During the civil war, Wildhammers and Dark Irons were banished from Ironforge by Bronzebeards. Wildhammer warriors traveled north and founded their own kingdom of Grim Batol.|n|nAfter some years, Dark Irons tried to strike back at both clans. But Wildhammers were victorious again, and so were Bronzebeards.|n|nHowever, Dark Iron empress Modgud had left an evil stain on Grim Batol, and the Wildhammers had to re-settle, this time in the lush forests of the Hinterlands.|n|nThis war have taught the two clans something. In the Valley of Kings in Loch Modan, there is a monument to Wildhammer and Bronzebeard friendship, and while rivalries would continue, we did not raise arms against one another ever again.|n|nCan't say the same about Dark Irons unfortunately..."
	text["DwarfEventWarofThreeHammersDarkIron"]="During the civil war, Dark Irons and Wildhammers were banished from Ironforge by Bronzebeards. After some years, Dark Irons tried to strike back at both clans. But Bronzebeards were victorious again, and so were Wildhammers.|n|nHaving retreated back to the Redridge Mountains, yer former emperor Thaurissan sought to protect himself from the fury of the two united clans. He summoned an ancient power sleeping beneath the Redridge Mountains.|n|nFreed by Thaurissan's call, Ragnaros the Firelord erupted into being. Ragnaros' apocalyptic rebirth into Azeroth shattered the Redridge Mountains and created a raging volcano at the center of the devastation. The volcano is now known as Blackrock Mountain.|n|nMany of the surviving Dark Irons were ultimately enslaved by Ragnaros and his elementals. Your former brethren remain within Blackrock to this day."

	text["DwarfEventFirstWar"]="Orcs came from another world, lad. These bloodthirsty beasts have ravaged the human city of Stormwind some twenty years ago."
	text["DwarfEventFirstWarStandard"]="The Alliance was not officially formed during the First War. When rumors have reached Khaz Modan, most have thought that orcs are a minor threat, like gnolls or murlocs..."	
	text["DwarfEventFirstWarPriestPaladin"]="The Alliance was not officially formed during the First War. It may seem strange, knowing that humans are our most valuable allies who have introduced us to Holy Light. But many in Khaz Modan have thought that orcs are a minor threat, like gnolls or murlocs..."	

	text["DwarfEventSecondWar"]="Second War immediately followed the First one. The orcs have bolstered ranks of the Horde with forest trolls, orges, and goblins, and continued to advance north. After devastation of Stormwind City, the whole continent was in danger of facing the same fate."
	text["DwarfEventSecondWarBronzebeard"]="The denizers of Azeroth - Bronzebeards, Wildhammers (not a minute too late!), gnomes, humans of the Seven Kingdoms, and high elves - have stood together against the Horde. Ironforge was besieged, and the rest of Khaz Modan fell to the orcs, including even Wetlands...|n|nBut after a long and bloody war, we emerged victorious."
	text["DwarfEventSecondWarWildhammer"]="Two years of Second War had to pass before ye Wildhammers realized that ye must join the Alliance!|n|nWhen Horde advanced to Wetlands, they had to face Wildhammer gryphon riders. Ye feral dwarves feared no enemy - and relied upon no friend. Ye had allied yerselves only with the elves of Quel'Thalas at the time, distrusting both Bronzebeards and the humans alike.|n|nHowever, after Horde assaulted Aerie Peak itself and the Alliance aided the Wildhammers in repelling the attack, ye Wildhammers isolationist point of view changed.|n|nWildhammers greatly aided the Alliance in Second War, and later freed the dragons who were forced to serve Horde in it, thus restoring completely the Alliance control over the air."
	text["DwarfEventSecondWarDarkIron"]="During First War, Blackrock Spire was the headquarter of the orcs Shadow Council, who made a truce with ye Dark Irons and Ragnaros's lieutenants. Afterwards, however, the Blackrock clan moved in.|n|nEven though Horde was crushed in Second War, some of the Blackrock clan never gave up. Reunited under the banner of Dark Horde, they and some of their old allies still wage war against Dark Irons for control over the Blackrock Mountain, and against the Alliance in Burning Steppes and Redridge."

	text["DwarfEventThirdWar"]="After a decade of peace, the plague happened. Kingdom of Lordaeron, former capital of the Alliance, found itself infested by the undead.|n|nArthas, prince of Lordaeron, travelled to Northrend with the mission to stop it. There, he is known to have met his friend Muradin Bronzebeard, brother of the Ironforge King Magni and one of the founding members of the dwarven Explorers' League.|n|nNo one knows exactly what happened there, but Muradin never returned from Northrend, and Arthas did - changed... Young paladin became a death knight, and he led the undead to ravage his own Kingdom."
	text["DwarfEventThirdWarStandard"]="Survivors of Lordaeron, as well as the other members of the Alliance, sailed across the Sea to Kalimdor. There, the final battle of the Third War happened. The undead turned out to be mere servants of the demons of Burning Legion. The Horde turned out to be able to listen to a reason, and to assist the Alliance heroes in saving the world.|n|nUltimately, the united forces of dwarves, humans, elves, orcs, trolls, tauren were able to defeat the demons during the Battle for Mount Hijal."	
	------------------------------------------------------------
	------------------------------------------------------------
	------------------------------------------------------------		
	--first date is beginning of event + 18; recent events are exception 
	text["HumanAge18-23"]="\"Four years have passed since the mortal races banded together and stood united against the might of the Burning Legion\".|n|nYour childhood was quite peaceful, but during your teenage years the world was shackled by the demonic invasion known as Third War. Perhaps the stories of the Hijal veterans have made you hungry for heroic deeds, or maybe the horrors of the war have influenced your decision to become an independent adventurer.|n|nIn any case, you are an adult now, and your future is in your hands..."	
	text["HumanAge23-33"]="\"Four years have passed since the mortal races banded together and stood united against the might of the Burning Legion\".|n|nYou were an adult when these events, known as Third War, took place.|n|nYou parents might have told you that the orcs are the greatest enemy the Alliance have ever faced, but you know that there are greater horrors."	
	text["HumanAge33-39"]="You were lucky enough to have a relatively peaceful youth. The orc invaders were defeated in the Second War, and only a few years ago the world have faced the wrath of their former masters - demons of the Burning Legion.|n|nYou know that the eternal peace is impossible, but you have at least felt the taste it."
	text["HumanAge39-43"]="When the orcs have attacked Azeroth and ravaged the city of Stormwind, you were a teenager. But by the time the Alliance of human kingdoms, dwarves, gnomes and high elves was formed, you had grown up already.|n|nThe Second War was the great victory of your youth. A decade of relative peace followed, and only a few years ago the world have faced the wrath of demons of the Burning Legion, former masters of orcs.|n|nYou know that even if an enemy is defeated, there is a chance that a greater foe lurks in shadows, only waiting for the proper moment to attack..."
	text["HumanAge43-61"]="When the orcs have attacked Azeroth and ravaged the city of Stormwind, you were already an adult. The Second War have followed, and the Alliance was victorious this time. After only a short break, the former orcish masters - the demons of the Burning Legion - has launched another invasion.|n|nYou have witnessed all three great Wars, and you know how dangerous this world can be."
	text["HumanAge61-80"]="A lot of stuff took place during your life. Gurubashi War between the Kingdom of Stormwind and the trolls of Stranglethorn, that is rumored to have been won by a single archmage - Medivh was his name. Orcish invasion, known as First War, in which the same Medivh has assisted the orcs. The defeat of orcs in the Second War. You have even heard that the spirit of Medivh has played some role in the recent demonic invasion that people call Third War!|n|nBut apparently the chaotic and dangerous nature of this world only amuses you. You are ready to be an adventurer again, and only a fool would call you \"retired\"."
	-----------------------
	text["HumanHomeKingdom"]="You are in the lands of Stormwind, " ..Lorehelper_VarFrame.name.. ", but were you born here? |n|nHundreds of years ago, a mighty human Empire of Arathor existed. Over the course of time, however, the Empire began to disintegrate, and its seven city-states became the Seven Kingdoms. |n|nWhich Kingdom are you from?"
	text["HumanDalaranMage"]="I could have guessed that the mage like you comes from the magocratic Kingdom of Dalaran...|n|nThe Kingdom was not a mere part of the Alliance and the wars it led. Hundreds of years ago, humans learnt from the high elves of Silvermoon that the abuse of magic inadvertently tears open rifts in reality. Through such rifts, a horrific demons can enter our world. The Order of Tirisfal was founded in order to protect Azeroth from this threat...|n|nIt all barely matters now. The city was ravaged during the Third War, by the very demons its leaders thought they know how to defend from. Its ruins are now covered by the magical barrier, and some wizards still lurk around them, their intentions unknown.|n|nWhile some mages live the past, some prefer the present. Apparently you are one of the latter, mage of the Alliance."
	text["HumanDalaranNonMage"]="The Kingdom of Dalaran, ruled by mages, but inhabited also by merchants, craftsmen, "..Lorehelper_VarFrame.class.."s...|n|nThe Kingdom was not a mere part of the Alliance and the wars it led. Hundreds of years ago, humans learnt from the high elves of Silvermoon that the abuse of magic inadvertently tears open rifts in reality. Through such rifts, a horrific demons can enter our world. The Order of Tirisfal was founded in order to protect Azeroth from this threat...|n|nIt all barely matters now. The city was ravaged during the Third War, by the very demons its leaders thought they know how to defend from. Its ruins are now covered by the magical barrier, and some wizards still lurk around them, their intentions unknown.|n|nWhile some, like those mages, live the past, some prefer the present. Apparently you are one of the latter."
	text["HumanHomeKingdomAlterac"]="Oh, you are one of the Alteraci? I would not mention it to strangers if I were you. Many still look down on Alteraci after Aiden Perenolde, the King of Alterac, has betrayed the Alliance in the Second War to ally with the Orcish Horde. After Perenolde's treachery was uncovered, the Alliance army has destroyed the city of Alterac. |n|nAlteraci survivors, however, continued to seek revenge upon Alliance even after the end of the Second War. Those loyal to the Kingdom and its old nobility are now known as Syndicate. But you are smarter than them, aren't you?"
	text["HumanHomeKingdomGilneas"]="Genn Greymane, the ruler of Gilneas, was never a strong supporter of the Alliance. Gilneas did assist in the Second War, but have left the Alliance afterwards.|n|nAttempting to forever remove his nation from what he considered \"other people's troubles\", Greymane barricaded the majority of Gilneas behind the Wall. But when the undead Scourge have invaded the neighbouring Lordaeron, the Wall was not enough to stop the walking dead.|n|nGreymane tried to use a \"secret weapon\" of his court archmage Arugal against the undead. The weapon, however, has only made things worse, for the weapon were worgen - wolfmen who soon have turned against the people of Gilneas.|n|nI bet that you are happy to have escaped the Kingdom years ago. Not much is known about the fate of those still locked behind the Wall."
	text["HumanHomeKingdomKulTiras"]="Howdy, sailor!|n|nThe island of Kul Tiras was once a great place to live at. The fleet of its ruler, Grand Admiral Daelin Proudmoore, have re-established the Alliance control of the sea during the Second War. On the vessels of Kul Tiras Jaina Proudmoore, the daughter of Daelin, have lead many hundreds of people of the Alliance across the sea, to Kalimdor, where the invaders of the Burning Legion were ultimately defeated.|n|nThe heroic tale ends abruptly. The Grand Admiral was slaughtered by the Horde during the battle for Theramore, Kul Tiras' fortress in Kalimdor - his daughter's peace pact with the Horde intact...|n|nSome Kul Tiran still fight with the Horde near Durotar, their capital. Some rumored to remain on the island. And some, like you, feel more comfortable on the solid ground."
	text["HumanHomeKingdomLordaeron"]="Oh, a Lordaeron refugee...|n|nNot everyone remembers the days of Lordaeron glory - the Kingdom being the uniting force for the Alliance, victory in the Second War. Not everyone remembers the brave young paladin, Arthas, Prince of Lordaeron. But everyone knows the story of Arthas turning against his people, killing his father, and leading armies of the undead to destroy the Kingdom...|n|nYour Kingdom is no more, and the living dead are all its inhabitants. Some undead have recently united with the Horde, and the catacombs of your old capital house their abominations.|n|nMany Lordaeronians are now members of Scarlet Crusade that continues the war against the undead. They are quite fanatic though, and would likely kill you on sight.|n|nBut I know that you are not infected with the undead plague. Make yourself comfortable - refugees are welcome here."
	text["HumanHomeKingdomStormwind35-"]="So you are local.|n|nYou are perhaps too young to remember the old city of Stormwind... It was beautiful - until the orcs have destroyed it in the First War. But now it again stands in all its glory, thanks to the aid of the Alliance and the efforts of the builders of Stonemason Guild.|n|nI should not have mentioned the Stonemasons... Let us, uhm, discuss something else.|n|nSince the fall of Lordaeron, the kingdom of Stormwind has become the strongest bastion of humanity and the most powerful nation within the Alliance. No Kingdom is without its troubles, but we need a Stormwindian like you to continue to prosper - for the Alliance, and for all the humans!"
	text["HumanHomeKingdomStormwind35+"]="So you are local.|n|nYou must be old enough to remember the old city of Stormwind... It was beautiful - until the orcs have destroyed it in the First War. But now it again stands in all its glory, thanks to the aid of the Alliance and the efforts of the builders of Stonemason Guild.|n|nI should not have mentioned the Stonemasons... Let us, uhm, discuss something else.|n|nSince the fall of Lordaeron, the kingdom of Stormwind has become the strongest bastion of humanity and the most powerful nation within the Alliance. No Kingdom is without its troubles, but we need a Stormwindian like you to continue to prosper - for the Alliance, and for all the humans!"
	text["HumanHomeKingdomStromgardeWarrior"]="Proud Stromic warrior here I see! Are you one of those who say \"Alliance of Stromgarde\" instead of \"Alliance of Lordaeron\"? Yes, both of the Kingdoms were the Alliance founders...|n|nStromgarde was once the capital of the human Empire, and later a strong Kingdom of humans. These days are gone. The Kingdom has stood strong against the Horde, the Scourge, the Alteraci traitors known as Syndicate - but the doom has come from the inside. The Kingdom ruler, Thoras Trollbane, was murdered by his son, Galen, who sought the throne of Stromgarde for himself. After the treachery, the Syndicate and the ogres managed to occupy much of the weakened Kingdom.|n|nArmies of Stromgarde still maintain a base of operations at the crevasse known as Refuge Pointe, as well as portions of the devastated capital city itself. Stromics are the founders of the League of Arathor, which is fighting to free the rest of the Arathi Highlands, the Arathi Basin, and its many resources from the hands of the Horde.|n|nI am sure you will see your compatriots again in Arathi one day."
	text["HumanHomeKingdomStromgardeNonWarrior"]="\"The warriors' nation of Stromgarde\" they say, but I see that you are not a warrior. Of course, each Kingdom needs "..Lorehelper_VarFrame.class.."s too...|n|nStromgarde was once the capital of the human Empire, and later a strong Kingdom of humans. These days are gone. The Kingdom has stood strong against the Horde, the Scourge, the Alteraci traitors known as Syndicate - but the doom has come from the inside. The Kingdom ruler, Thoras Trollbane, was murdered by his son, Galen, who sought the throne of Stromgarde for himself. After the treachery, the Syndicate and the ogres managed to occupy much of the weakened Kingdom.|n|nArmies of Stromgarde still maintain a base of operations at the crevasse known as Refuge Pointe, as well as portions of the devastated capital city itself. Stromics are the founders of the League of Arathor, which is fighting to free the rest of the Arathi Highlands, the Arathi Basin, and its many resources from the hands of the Horde.|n|nI am sure you will see your compatriots again in Arathi one day."
	-----------------------
	text["HumanStandardAvoided"]="You were not much affected by these events."
	text["HumanStandardLostSomeone"]="You have lost someone you loved during these events."
	text["HumanStandardParticipated"]="You did fight in this war. Luckily, survived."
	text["HumanStandardLostEverything"]="You have suffered a lot during these horrible events. The scars of this war will forever remind you of those you loved and lost, of burnt houses, of crying children, of fresh graves..."
	text["HumanZoneAvoided"]=""
	text["HumanZoneLost someone"]="This is where the life of someone you loved has come to an end."
	text["HumanZoneParticipated"]="You have been fighting here. Looks peaceful now, but is it for long?"
	text["HumanZoneLost everything"]="This is where you suffered a terrible loss..."

	text["HumanZoneWestern Plaguelands"]="All the way from here to the east are the lands haunted by the undead Scourge. To the west, in Tirisfal Glades, the undead of Horde reside.|n|nBefore the plague, these were lands of Lordaeron. But then the humans of the area have been decimated by the undead. Most of the survivors fled, some have joined the Scarlet Crusade - the order devoted to exterminating the undead. Their fanatism might have caused just as many human deaths as the ruthlessness of the Scourge..."
	text["HumanZoneTooltipWestern Plaguelands"]="A paladin is rumored to live in an exile far to|nthe north, on the shores of the Thondroril River."
	text["HumanZoneHome KingdomLordaeron"]="Even if your nerves are made of steel, it still must be painful to see what your homeland has become."
	text["HumanZoneDustwallow Marsh"]="The city of Theramore, the main bastion of humanity on Kalimdor, was founded four years ago, when Jaina Proudmoore led her people here to settle down after the battle with Archimonde at Mount Hyjal. Jaina's humans rapidly extended into the swamp, building fortified guard towers along the road to the Barrens.|n|nThe people of Theramore are deeply loyal to Jaina Proudmoore, especially those who fought under her in the Third War."
	text["HumanZoneHome KingdomKul Tiras"]="This place is special for Kul Tiran. Lord Admiral Daelin Proudmoore was slain on the streets of Theramore, fighting the orcs, just as he believed every human should. Many Kul Tiran will never forgive his daughter Jaina who stood aside..."
	text["HumanZoneSilverpine Forest"]="In the north part of Silverpine, the Wall of Graymane separates the Kingdom of Glineas from the rest of the world. Apparently, it did help the Kingdom to survive the plague of undeath that have destroyed the neighbouring Lordaeron. But not much is known about the fate of those still behind the Wall."
	text["HumanZoneHome KingdomGilneas"]="Who knows, maybe one day these gates will open again and your home Kingdom will again be an influential part of the Alliance."
	text["HumanZoneAlterac Mountains"]="Once upon a time, there were two human Kingdoms in this area. Alterac lies in ruins, as retaliation was swift after it was discovered that its ruler had betrayed the Alliance in Second War. Dalaran was ravaged by the demon lord, Archimonde the Defiler, when he has entered our world during Third War."
	text["HumanZoneHome KingdomAlterac"]="Your former lords, nobles of Alterac, now lead a criminal organization known as Syndicate."
	text["HumanZoneHome KingdomDalaran"]="However, something is still happening near the magic barrier that covers your former Dalaran home now. Maybe one day, by the power of Arcane, the city will rise from ashes."
	text["HumanZoneArathi Highlands"]="The Arathi Highlands were once the cradle of human civilization. After the Empire of Arathor has collapsed, the the guardsmen of its capital founded a new martial kingdom known as Stromgarde.|n|nStromgarde is now overrun by the Syndicate and the ogres. The remnant of the Stromgarde army was forced to flee and take refuge in a small canyon to the north - Refuge Pointe. They are the League of Arathor, and they fight an endless battle for their city, as well as for Arathi Basin that Horde seeks to claim for itself."
	text["HumanZoneHome KingdomStromgarde"]="Since you are Stormic, I guess you are eager to join this battle."
	--	text["HumanZoneBlasted Lands"]="This is the area where the orcish Horde first entered Azeroth through the Dark Portal, followed soon by their attack on the human lands to the northwest, and, ultimately, by their victory in First War."
	text["HumanZoneRedridge Mountains"]="This seemingly-idyllic part of Stormwind Kingdom was one of the important battlefields of First War. Eventually conquered by the orcish Horde, it has only returned to the Alliance a few years later.|n|nEven now, \"Dark Horde\", remnants of the old Horde, controls the Burning Steppes to the north and plagues Redridge with constant attacks."
	text["HumanZoneBurning Steppes"]="Blackrock Spire served as an orc stronghold during First and Second War. Orcs that live here today do not honor Horde's truce with the Alliance even formally.|n|nIt was in Burning Steppes where the hero of humankind, Anduin Lothar, was slain by cowardly orcs. Lothar's death turned the tide in the unexpected direction, and spurred the Alliance on to crush the failing Horde."
	text["HumanZoneWestfall"]="This rich land has lain fallow since Second War, and years of neglect and conflict have not improved the situation. Westfall is a region of rolling pastures and farms that were once beautiful and green, but now have become barren with drought due to maltreatment at the hands of Defias Brotherhood.|n|nOnly the People's Militia, a volunteer military organization, has risen to stand in the way of the thugs, to strike back and regain what has been stolen."
	text["HumanZoneTooltipWestfall"]="Do not forget to talk to Gryan Stoutmantle,|nleader of the People's Militia and \"mayor\"|nof Sentinel Hill!"
	text["HumanZoneAshenvale"]="Forests of Ashenvale is where the Alliance has first met the night elves. The contact was not a peaceful one... But later, understanding that demons of Burning Legion are a greater evil, night elves have joined forces with Alliance and Horde to repel the demonic invasion."
	text["HumanZoneStranglethorn Vale"]="Jungle trolls were enemies of the Kingdom of Stormwind since its foundation. The last large conflict, known as Gurubashi War, has happened about forty years ago.|n|nNow trolls seem to be at bay, but who knows what vile plans they plot in their misterious half-ruined towns of Stranglethorn..."

	text["HumanEventGurubashiWar"]="The short but violent conflict between the Kingdom of Stormwind and trolls of Stranglethorn is known as Gurubashi War."
	text["HumanEventGurubashiWarStandard"]="The Gurubashi War was fought in lands of Stormwind, far from your home Kingdom."	
	text["HumanEventGurubashiWarStormwind"]="Trolls laid siege to Stormwind City. The army of mutated soldiers created by Warlord Zan'non rushed into the city, and many humans, including King Barathen Wrynn himself, were killed in battle.|n|nBut then, Medivh the Guardian, a friend of Prince Llane and Commander Anduin Lothar, laid waste to the troll forces with unmatched fire, frost, and arcane magics.|n|nMedivh, Llane and Lothar were praised as heroes, and indeed they were. But some rumor that it was actually due to their recklessness that the war was sparked in the first place..."	
	text["HumanEventFirstWar"]="It all started with rumors. Rumors of greenskin monsters in the Swamp of Sorrows. Most were dismissed as tales - oh, how wrong those dismissing them were...|n|nFirst War between humans of Stormwind and orcs who came out of the Dark Portal was only the beginning of chain of events that would forever change Azeroth."
	text["HumanEventFirstWarStandard"]="The Alliance was not officially formed during the First War: rulers of the six Kingdoms have perhaps thought that orcs are a minor threat Stormwind can deal with."	
	text["HumanEventFirstWarStormwind"]="After three years of First War, the once-mighty Kingdom of Stormwind was nothing more than a smoking ruins. The orcish Horde continued to ravage the countryside and claimed the surrounding lands for its own."	
	text["HumanEventSecondWar"]="Second War immediately followed the First one. The orcs have bolstered ranks of the Horde with forest trolls, orges, and goblins, and continued to advance north. After devastation of Stormwind City, the whole continent was in danger of facing the same fate."
	text["HumanEventSecondWarStandard"]="The denizers of Azeroth - humans of the Seven Kingdoms, dwarves, gnomes, and high elves - have stood together against the Horde. After a long and bloody war, we emerged victorious."
	text["HumanEventThirdWarPlague"]="After a few years of peace, the Alliance began to fall apart. The high elves of Silvermoon brusquely rescinded their allegiance to the Alliance, and Gilneas and Stromgarde seceded as well. Busy with politics, the rulers of the Alliance missed the dawn of a greater horror.|n|nThe plague. It was not a natural disease but a part of a vile plan. The plague have been turning people into zombies, and what is worse - there was a mastermind behind them.|n|nThe armies of undead, the Scourge, have been destroying everything on their path - and with every human soldier dying in battle, another undead soldier rose to strengthen the Scourge."
	text["HumanEventThirdWarPlagueStandard"]="The plague of undeath has put an end to the Kingdom of Lordaeron. Humans were not the main target of the undead though. The Scourge was to follow the plan of the Burning Legion and summon its demons into Azeroth..."
	text["HumanEventThirdWarPlagueLordaeron"]="The plague of undeath has put an end to the Kingdom of Lordaeron. Prince Arthas has become a death knight monstrocity, and led the undead armies to destroy his own Kingdom. Thosands of people perished, and thosands were raised as zombies...|n|nHumans were not the main target of the undead though. The Scourge was to follow the plan of the Burning Legion and summon its demons into Azeroth."
	text["HumanEventThirdWarPlagueDalaran"]="The plague of undeath has put an end to the Kingdom of Lordaeron. The lich Kel'Thuzad then launched a siege against Dalaran. His aim was to capture an artifact - the Book of Medivh - and he succeeded. Drawing on all the power contained within the Book allowed Kel'Thuzad to create a rift from which a horrible demon, Archimonde the Defiler, was able to enter Azeroth.|n|nArchimonde made an example of what would happen to anyone who would resist the Burning Legion. He picked the city of Dalaran and proceeded to destroy it single-handedly with his magic."
	text["HumanEventThirdWarKalimdor"]="Demons of the Burning Legion, led by Archimonde the Defiler, followed the undead Scourge to Kalimdor, bent on destroying Nordrassil, the World Tree. The Alliance heroes sailed across the Great Sea as well, ready to fight not for glory of their Kingdoms, but for Azeroth itself."	
	text["HumanEventThirdWarKalimdorStandard"]="Many humans from different Kingdoms, as well as the other members of the Alliance, have followed Jaina Proudmoore to Kalimdor. There, a short-lived alliance between them and the orcs, trolls, and taurens of the New Horde was formed.|n|nUltimately, the demons were defeated in a bloody Battle for Mount Hyjal."
	text["HumanEventThirdWarKalimdorKulTirasLordaeron"]="Many survivors of Lordaeron, as well as the other members of the Alliance, have joined Jaina Proudmoore when she led the fleet of Kul Tiras to Kalimdor. There, a short-lived alliance between them and the orcs, trolls, and taurens of the New Horde was formed.|n|nUltimately, the demons were defeated in a bloody Battle for Mount Hyjal."
	------------------------------------------------------------	
	------------------------------------------------------------
	------------------------------------------------------------
	text["TrollStandardAvoided"]="You be not there back then, mon."
	text["TrollStandardLostSomeone"]="You be losing someone when it all be."
	text["TrollStandardParticipated"]="You be fighting dis war. Good for you you be live."
	text["TrollStandardLostEverything"]="You be suffering a lot in dis war. Some wounds never heal. Bwonsamdi be watching da spirits of da many dead..."

	text["TrollZoneAvoided"]=""
	text["TrollZoneLost someone"]="You be losing someone here."
	text["TrollZoneParticipated"]="You be fighting here. Be peaceful now, but be it for long?"
	text["TrollZoneLost everything"]="You be suffering a lot here. Bwonsamdi be watching da spirits of da many dead..."

	text["TrollZoneTribeBad tribe"]="Be you living here in evil tribe before? It be of no matter now. They be now killing you if you let them to."
	text["TrollZoneEastern Plaguelands"]="Here and to da west be da lands haunted by da undead Scourge. Further to da west, in Tirisfal Glades, da Undercity is located - da undead capital of da Horde.|n|nBefore da plague, these were lands of Mossflayer trolls and humans. Of course, they be always fighting. But not many survived the plague, and now Mossflayer have to fight their own living dead."
	text["TrollZoneTooltipEastern Plaguelands"]="Da human paladin is rumored to live in exile far to|nda northwest, on da shores of Thondroril River.|nBe one of those paladins who'd lend a helping hand|nto anyone, be it human or troll."
	text["TrollZoneDustwallow Marsh"]="Our allies, da ogres of Stonemaul, be living nearby, in Brackenwall Village. Our enemies, humans, have da city of Theramore in da area, and fortified guard towers along da road.|n|nRight now, at least officially, there be a truce in this region. But just few years ago, human admiral Proudmoore and his Kul Tiras marines be launching a violent attack on da Horde."
	text["TrollZoneAshenvale"]="Forests of Ashenvale is where da Horde has first met da night elves. The contact be not a peaceful one... But later, understanding that demons of Burning Legion be da greater evil, night elves be joining forces with Alliance and Horde to repel da demonic invasion."
	text["TrollZoneStranglethorn Vale"]="Demonic orcs be trying to claim Stranglethorn in First War, but trolls be fighting back, and orcs be retreat.|n|nDis lands be da home of many tribes. We Darkspear be living here before da orge-mages be occupying our lands. Bloodscalp and Skullsplitter, our mortal enemies, be still living here. Be dark Gurubashi tribe in da ancient city of Zul'Gurub.|n|nRecently, da great Zandalari be also coming to Yojamba Isle just off the shore."
	text["TrollZoneTribeDarkspear"]="We Darkspear no longer belong to Stranglethorn or to islands around. Our home be Durotar, our home be with da Horde."
	text["TrollZoneTribeZandalari"]="Do you know why be your mighty Zandalari brethren here?"
	text["TrollZoneThe Hinterlands"]="Hinterlands be da home of many tribes. Revantusk be friends to da Horde, while Witherbark and Vilebranch be our enemies.|n|nJintha'Alor be da second largest city of da forest trolls, second only to wondrous Zul'Aman. Shame be it inhabited by Vilebranch savages."
	text["TrollZoneTribeRevantusk"]="You be one of da Revantusk. Visit your home village and see if they be needing help against Witherbark and Vilebranch."
	text["TrollZoneTooltipThe Hinterlands"]="Qiaga the Keeper atop the Altar of Zul be rumored|nto hold da very ancient and sacred Mallet."
	text["TrollZoneDun Morogh"]="There be trolls even here, in lands of dwarves! Da tribe's name is Frostmane. Be savage trolls, be no friends of da Horde."
	text["TrollZoneSwamp of Sorrows"]="After fall of da Gurubashi Empire, da renegade faction of trolls, Atal'ai, fled into Swamp of Sorrows and built a large Temple of Atal'Hakkar. They be da Blood God servants. Their plans be very bring his rage to da world.|n|nGreen dragons be learning about the evil of Atal'ai, and they be drowning the Temple."
	text["TrollZoneTooltipSwamp of Sorrows"]="There be a spirit of orcish hero|non da border with Blasted Lands."
	text["TrollZoneTanaris"]="Tanaris be part of da ancient Gurubashi Empire. When da continent be split in two many thousands of years ago, it became da desert.|n|nBut da trolls still be living here, trolls of Sandfury. They be savage trolls though. They be never join da Horde, and to be killed on sight they be."
	text["TrollZoneTooltipTanaris"]="Yeh'kinya in Steamwheedle Port be rumored to know|na lot about ancient prophecies."
	text["TrollZoneDarkshore"]="Dis be lands of night elves. But trolls be living here too!|n|nShatterspear village be not easy to reach. But if you be finding them, you be enjoying da best dance in Azeroth! Be forgetting about dis cruel world and be dancing all day long..."
	text["TrollZoneTribeShatterspear"]="But I forgot I be talking to one of Shatterspear. Be you now coming back home for some dance?"
	text["TrollZoneHillsbrad Foothills"]="Dis is where the great Warlord of da Amani forest trolls, Zul'jin, be held captive by humans. Orcs be freeing Zul'jin, and forest troll be joining da old Horde in Second War."

	text["TrollAgeYoung"]="\"Four years have passed since the mortal races banded together and stood united against the might of the Burning Legion\".|n|nYou be da child then, mon. Now you be grown up. Demons may be defeated, but there be more enemies. We Darkspear trolls be protect our tribe and fight for da Horde!"
	text["TrollAgeThirdWar"]="\"Four years have passed since the mortal races banded together and stood united against the might of the Burning Legion\".|n|nWe Darkspear trolls be fighting with those demons. We stood alongside our new orc and tauren friends - we be da Horde.|n|nHumans be fighting with da demons too. But humans be treacherous. Betrayed in da past, will betray again."
	text["TrollAgeBetweenWar"]="Remember when old Horde be losing Alliance in Second War? We Darkspear trolls be not fighting. Alliance be no good, but old Horde be nothing but demonic pawns.|n|nBut forest trolls be fighting. After losing, dark time be for forest trolls. Dark time for our Revantusk friends. Dark time for our Amani enemies. Always dark time when you be losing da war.|n|nThen be da New Horde born. Thrall be leading da Horde now. Thrall be da wise orc. Four years ago, we Darkspear trolls be honored to fight for da New Horde, against the demons!"
	text["TrollAgeSecondWar"]="Old Horde be no good, mon. Old Horde be friends with ogres, they be teach them dark magic. Da ogre mage be drive us Darkspear trolls from our home in Stranglethorn.|n|nBut old Horde be nothing but demonic pawns. Then be da New Horde born. Thrall be leading da Horde now. Thrall be da wise orc. Four years ago, we Darkspear trolls be honored to fight for da New Horde, against the demons!"
	text["TrollAgeOld"]="You be no young troll, mon. You maybe remember days when no orcs there be. Then da orcs come and fight da humans. Then forest trolls be fighting for orcs, elves be fighting for humans.|n|nWe Darkspear trolls be not fighting. Alliance be no good, but old orcs be nothing but demonic pawns.|n|nNow da Horde is different. Thrall be leading da Horde now. Thrall be da wise orc. Few years ago, we Darkspear trolls be honored to fight for da New Horde, against the demons!"
	------------------------------------------------------------
	text["TrollTribe"]="We trolls be usually loyal to our tribe. But sometimes tribes do wrong, then you must do right.|n|nYou be one with Darkspear now, but what be the tribe you be born in?"
	text["TrollTribeDarkspear"]="I see now, you be Darkspear troll.|n|nWe be never a large tribe, but we not be weak. We be have a lot of enemies. There be Sea Witch on Darkspear islands - our islands. She be controlling murlocs, many murlocs there be. Our leader Sen'jin be dead from their claws...|n|nBut Sen'jin be had a vision. Be said that the future of Darkspear is with da orc Thrall and da Horde. So we be give blood oath to da Horde, and serve da Horde we be."
	text["TrollTribeRevantusk"]="You be of our Revantusk friends. Revantusk be da only forest trolls who be friends with us Darkspear.|n|nThey be respect the lost Amani leader, Zul'jin. Zul'jin be fighting with old Horde, against humans and elves. Revantusk be think they still must be serving da Horde, da New Horde lead by Thrall, Revantusk think this is what Zul'jin would do.|n|nWe Darkspear not be friends with Amani, we be not sure Zul'jin would be da friend of Thrall. But I mean no offense, mon. We be glad to be friends with you Revantusk."
	text["TrollTribeShatterspear"]="You be crazy dancing troll! Do not be get me wrong, mon. Nothing better than da good dance.|n|nI know your village be far away, in lands of elves it be. Must be boring there. You be dance all day, be maybe good for month or two. But then da heart wants more, be I right mon?"
	text["TrollTribeZandalari"]="We Darkspear be honored to have one of Zandalari fighting with us. Da ancient tribe Zandalari be. As ancient as trolls be, and trolls be very ancient!|n|nSome say you Zandalari rule da world from your distant islands. You be da legendary tribe.|n|nBe rumors that some of your tribe be on an island near our old home in Stranglethorn. Not as distant as usual with you Zandalari dat island be! Maybe you see your tribe there one day."
	text["TrollTribeBad"]="There be many bad troll tribes. Be bad tribe far to the south in da desert. Be bad tribes across da Sea.|n|nIn Stranglethorn be da crazy Blood God worshippers. Be tribes still serving old Horde in Blackrock. Be trolls in lands of plague. Be tribes dat fight our Revantusk friends in Hinterlands. Some trolls be in lands of dwarves. They kill dwarves, but they would kill da Horde just as well!|n|nYou be right to leave your tribe. We Darkspear need smart trolls like you. Now if you see trolls of your old tribe, kill them, or be killed and have your heart eaten."
	------------------------------------------------------------
	text["TrollEventGurubashiWar"]="It be long ago. Gurubashi trolls kill humans, humans kill da Gurubashi warlord. Gurubashi attack human city of Stormwind, and almost be win. But da human mage be powerful... Many trolls be dead."
	text["TrollEventGurubashiWarBadTribe"]="If you be of Gurubashi back then, you be remember dat war. Some humans have powerful magic. Humans be reckless with magic too. I heard dat mage fell victim to his powers in da end. It be not bringing da dead trolls back, but I be thinking you be glad to know."
	text["TrollEventGurubashiWarStandard"]="Gurubashi be fighting humans, but other tribes be not."
	text["TrollEventFirstWar"]="Orcs be come from another world, mon. Orcs be fooled by demons then, and be their blood slaves. Orcs be attack humans of Stormwind, and they crush da city."
	text["TrollEventFirstWarJungleTroll"]="For trolls of jungles, orcs be enemies then. Bleeding Hollow orcs be trying to claim Stranglethorn for themselves. But trolls be resist, be repel intruders!"
	text["TrollEventFirstWarStandard"]="Orcs be fighting humans. Humans are no good, but orcs be corrupt then. Most trolls not be fighting dat war."
	text["TrollEventSecondWar"]="After losing Stormwind, humans be retreat. Humans ally with other humans, with dwarves, and what is worse - with stinky elves!|n|nOrcs seek friends too. Old Horde be not only orcs, but also forest trolls, goblins, ogres even."
	text["TrollEventSecondWarForestTroll"]="Forest trolls be fighting in dat war. Zul'jin be leading Amani and Revantusk and other tribes. Be fighting elves of Alliance, be killing them many.|n|nBut then, Zul'jin be missing, orcs be losing, tribes be weak again..."
	text["TrollEventSecondWarStandard"]="Dat war be fought across the continent. But not in da jungle, and not on da islands. Demonic Horde be losing in da end."
	text["TrollEventThirdWar"]="Terrible demons be attacking our world five years ago. Orc Thrall be seeing da vision and be leading his people to Kalimdor. Orcs be allying with us Darkspear trolls, and with tauren.|n|nThen da Horde even makes peace with Alliance! Sacrifices sometimes be made to save da world..."
	text["TrollEventThirdWarDarkspear"]="We Darkspear be losing our islands to da Sea Witch, so we be following Thrall across da Sea, to da north of Kalimdor. Da Horde be fighting for Azeroth. Alliance helps.|n|nDemons be defeated in da lands of elves, on da Mount Hijal."
	text["TrollEventThirdWarStandard"]="Da Horde be fighting for Azeroth. Alliance helps.|n|nDemons be defeated in da lands of elves, on da Mount Hijal. We Darkspear celebrate victory with da Horde. Other troll tribes be staying in their lands."
	text["TrollEventWarTheramore"]="Thrall decided to stay in Kalimdor. Orcs be building da city of Orgrimmar to call da home.|n|nBut peace with Alliance be short. Jaina da human may be da friend of Thrall, but her father Daelin be not. His soldiers slay orcs and trolls just as it be Second War."
	text["TrollEventWarTheramoreDarkspear"]="We Darkspear make home on Echo Isles, but we be driven from our home again - dis time by humans. We be fighting for da Horde once more, and da Horde be victorious again!|n|nHumans be no more, only a few stubborn still fight. But Darkspear still cannot live on Echo Isles. We be betrayed by Zalazane, da best friend of our chieftain Vol'jin in da past.|n|nMaybe you be soon fighting with Zalazane and his dark magic, for da glory of our tribe."
	text["TrollEventWarTheramoreStandard"]="Our Revantusk friends be fighting with other tribes for their lands. Crazy Blood God worshippers be fighting to fill da world with blood and chaos. Every tribe fights for what they think be right.|n|nWe Darkspear fight with humans for our Isles. Humans now be no more."
	------------------------------------------------------------	
	------------------------------------------------------------
	------------------------------------------------------------
	text["TaurenZoneAvoided"]=""
	text["TaurenZoneLost someone"]="This is where the life of someone you loved has come to an end."
	text["TaurenZoneParticipated"]="You have been fighting here. Looks peaceful now, but is it for long?"
	text["TaurenZoneLost everything"]="This is where you suffered a terrible loss..."

	text["TaurenZoneThe Barrens"]="For countless generations, the tauren roamed the plains of the Barrens hunting the mighty kodo. Our tent cities were scattered across the landscape and changed with the seasons and the weather. We were united by a common hatred for our sworn enemy, the marauding centaur.|n|nNow, thanks to the Horde, the Barrens are truly ours. Centaurs are still a threat for travellers, but our settlements are well-protected from those beasts."
	text["TaurenZoneThousand Needles"]="The barren canyons of Thousand Needles have traditionally been the territory of several tauren tribes. We were forced to live precariously on the tips of the high mesas in order to avoid the large tribes of centaurs. Now, with the help of the Horde, we are fighting back against our enemies.|n|nDarkcloud Pinnacle, a large settlement of Grimtotem tribe, is located here. Let us hope that, despite their extreme views, we can still avoid an open conflict..."
	text["TaurenZoneGrimtotemYes"]="And you won't have to fight your own tribe."
	text["TaurenZoneDustwallow Marsh"]="Our allies, the ogres of Stonemaul, live nearby, in Brackenwall Village. Our enemies, humans, have a city of Theramore in the area, and fortified guard towers along the road.|n|nRight now, at least officially, there is a truce in this region. But just few years ago, human admiral Proudmoore and his Kul Tiras marines have launched a violent attack on the Horde."
	text["TaurenZoneDesolace"]="Legends say that Desolace was a once fertile grassland frequented by the shaman of the tauren tribes. They sought the Earthmother herself here. During this search, they have awakened an enormous earth elemental - Princess Theradras - whose insatiable hunger drought the land.|n|nWhat is worse, the centaurs were born by this horrible creature. Our war with centaurs would come to last for many centuries.|n|nPrincess Theradras is still rumored to exist in Maraudon, the place sacred by centaur. Some say she is behind them recently becoming even more agressive than ever."
	text["TaurenZoneTooltipDesolace"]="Rumors are, the Centaur Pariah in southern Desolace|nseeks someone to enter Maraudon."--redundant I think:|nThere are also those in Orgrimmar and, of course,|nin Shadowprey Village interested in this place.|nFinally, you may want to speak with an undead, Willow,|nwho lives in a hut nearby."
	text["TaurenZoneAshenvale"]="Forests of Ashenvale is where the Horde has first met the night elves. The contact was not a peaceful one... But later, understanding that demons of Burning Legion are a greater evil, night elves have joined forces with Alliance and Horde to repel the demonic invasion."

	text["TaurenAgeYoung"]="\"Four years have passed since the mortal races banded together and stood united against the might of the Burning Legion\".|n|nYou were just a child then. Now you have grown up. We have defeated the demons, because we were united - Horde and Alliance stood together to protect the world. We have then enjoyed a few years of peace.|n|nBut the eternal peace is impossible. Walk with the Earthmother, young tauren, when you face the challenges of today."
	text["TaurenAgeThirdWar"]="\"Four years have passed since the mortal races banded together and stood united against the might of the Burning Legion\".|n|nYou were an adult already, were you not? Orcs have come from across the Sea, lead by the wise shaman Thrall. With the help of the Horde, we got an upper hand in our centuries-old conflict with the centaur. We then repaid the debt by fighting together with the Horde against the demons who sought to destroy our world.|n|nA lot is so different for tauren now. No longer we are nomads, we have lands of Mulgore to call our home - and protect our home we shall..."
	text["TaurenAgeMiddleAge"]="You were nomading with your tribe, just as all the tauren have been for centuries. Centaurs were our enemies for as long as the eldest of us can remember.|n|nFew years ago, orcs have come from across the Sea, lead by the wise shaman Thrall. With the help of the Horde, we got an upper hand against the centaur. We then repaid the debt by fighting together with the Horde against the demons who sought to destroy our world.|n|nA lot is so different for tauren now. No longer we wander among the plains, we have lands of Mulgore to call our home - and protect our home we shall..."
	------------------------------------------------------------
	text["TaurenGrimtotem"]="Before we continue, I would like to ask you a question. Please do not deem it impolite, and please do not think that your answer will affect our future conversation. I would like you to feel safe and welcome, therefore I considered this introduction necessary.|n|nDo you belong to the Grimtotem tribe?"
	text["TaurenGrimtotemDruid"]="Some taurens have recently joined Cenarion Circle, the druidic organization that seeks to preserve balance in the nature. For thousands of years, it was lead by night elves.|n|nSome night elves, including Archdruid Fandral Staghelm, wanted to keep it exclusive. I guess that from our side, the leader of your tribe, Magatha Grimtotem, was opposed to such union as well.|n|nI think I speak for the majority of tauren when I say that peace and cooperation is better than conflict. If you agree, Druid, then maybe you will be revered by Cenarion Circle one day."
	text["TaurenGrimtotemShaman"]="The leader of your tribe, Magatha Grimtotem, is also a shaman. I heard her saying that \"the spirits are angry\" with the recent inclusion of orcs and trolls to our society, that the land is sick and requires \"purging.\"|n|nI am not sure if other Shamans would agree. But only the Earthmother knows how spirits really feel, so it is a subtle topic."
	text["TaurenGrimtotemHunter"]="The Great Hunt... It was the nature of the tauren for centuries. Now the world is more complex. We are a part of Horde, we maintain an unsteady peace with Alliance.|n|nI guess many would like to live in a simpler world of the past. I guess this is why the approach of the leader of your tribe, Magatha Grimtotem, who speaks of non-tauren as of \"lesser races\", is so appealing to many."
	text["TaurenGrimtotemWarrior"]="War with centaur... It was the nature of the tauren for centuries. Now the world is more complex. We are a part of Horde, we maintain an unsteady peace with Alliance.|n|nI guess many would like to live in a simpler world of the past. I guess this is why the approach of the leader of your tribe, Magatha Grimtotem, who speaks of non-tauren as of \"lesser races\", is so appealing to many."
	text["TaurenNonGrimtotemDruid"]="Some taurens have recently joined Cenarion Circle, the druidic organization that seeks to preserve balance in the nature. For thousands of years, it was lead by night elves.|n|nSome night elves, including Archdruid Fandral Staghelm, wanted to keep it exclusive. But taurens managed to prove their worth to the others.|n|nI think our Chieftain, Cairne Bloodhoof, is proud of that. Not only we are part of the mighty Horde, but we also try to build ties with Alliance. Though our disagreements with Alliance are many, we should always strive for peace - whenever possible, anyway..."
	text["TaurenNonGrimtotemShaman"]="Our society was always highly spiritual. Shamans like you consult the spirits, and the spirits guide us.|n|nThrall, Warchief of the Horde, is also a shaman. Our troll allies respect their shamans as well. I think it is safe to say that spirits connect the Horde."
	text["TaurenNonGrimtotemHunter"]="The Great Hunt... It was the nature of the tauren for centuries. Now the world is more complex. We are a part of Horde, we maintain an unsteady peace with Alliance.|n|nBut it does not mean the Great Hunt is over. Our Chieftain, Cairne Bloodhoof, leads the tauren to the brighter future. This future will not be easy, but the tauren never give up!"
	text["TaurenNonGrimtotemWarrior"]="War with centaur... It was the nature of the tauren for centuries. Now the world is more complex. We are a part of Horde, we maintain an unsteady peace with Alliance.|n|nBut it does not mean that the war is over. Our Chieftain, Cairne Bloodhoof, does promote peace, but only when peace is possible. When it is not, we are ready to fight again - for the glory of our tribes, and for the glory of the Horde!"
	------------------------------------------------------------
	text["TaurenEventThirdWar"]="Terrible demons invaded our world five years ago. Thrall, Warchief of the Horde, had a vision. He lead the orcish clans to Kalimdor, ancient home of the tauren.|n|nOrcs have helped us in our fight with centaur. This is how we joined the Horde. This is why we fought against demons as a part of the Horde - and even Alliance was fighting together with us..."
	text["TaurenEventThirdWarStandard"]="Tauren, orcs, trolls, humans, elves, dwarves - only thanks to the bravery of us all, the Battle for Mount Hijal was won, and the demons no longer pose threat to our existence."
	text["TaurenEventWarTheramore"]="After the war with demons was over, Thrall have decided to stay in Kalimdor. We tauren have decided to settle as well. Great tauren city of Thunder Bluff and great orcish city of Orgrimmar were built.|n|nBut, before long, another war has began. Human admiral Daelin Proudmoore and his soldiers attacked the Horde, still full with hatred even years after the end of Second War."
	text["TaurenEventWarTheramoreStandard"]="Thrall did try to maintain peace, but humans only cared for vengeance. Daelin did not even listen to his own daughter Jaina, who was in a truce with Horde.|n|nUltimately, the humans were defeated, the fanatic admiral slain, and city of Theramore returned to Jaina's hands. Having a human city in such proximity may feel uncomfortable, but at least humans of Jaina are not openly agressive."
	------------------------------------------------------------
	------------------------------------------------------------
	------------------------------------------------------------
	text["UndeadStandardAvoided"]="You were perhaps still a mindless slave of the Lich King back then."
	text["UndeadStandardLostSomeone"]="Must be funny to make friends even in undeath, only to lose them later?"
	text["UndeadStandardParticipated"]="You've been fighting in this war under the Dark Lady."
	text["UndeadStandardLostEverything"]="After losing your life, your body, most of your feelings, you perhaps thought you have nothing else to lose. But you were wrong, and during this war you have learnt the truer despair."

	--there is only one event for undeads (Dreadlords' fall), and it's not linked to a zone (happened in Tirisfal anyway)
	--[[	text["UndeadZoneAvoided"]=""
	text["UndeadZoneLost someone"]="You be losing someone here."
	text["UndeadZoneParticipated"]="You be fighting here. Be peaceful now, but be it for long?"
	text["UndeadZoneLost everything"]="You be suffering a lot here. Bwonsamdi be watching da spirits of da many dead..."--]]

	text["UndeadZoneWestern Plaguelands"]="All the way from here to the east are the lands haunted by the Scourge. To the west, in Tirisfal Glades, are the lands of Forsaken.|n|nScarlet Crusade has a stronghold on the north, in Hearthglen. Andorhal, on the other hand, is full of Scourge, lead by a powerful lich Araj the Summoner."
	text["UndeadZoneTooltipWestern Plaguelands"]="A human paladin is rumored to live in an exile far to|nthe north, on the shores of the Thondroril River.|nOne of those paladins who won't start|n exorcising you on sight."
	text["UndeadZoneLast living momentAndorhal"]="Perhaps its amusing to fight for your home town again - you are different, but the enemy is the same."
	text["UndeadZoneLast living momentHearthglen"]="Perhaps you were fighting the undead here. Now you are undead yourself, and denizers of Hearthglen are you mortal enemies. It is amusing how tables turn."
	text["UndeadZoneEastern Plaguelands"]="In the eastern part of Plaguelands, there is even more of the Scourge. Scarlet zealots only hold Tyr's Hand on the southeast, and small part of Stratholme city."
	text["UndeadZoneLast living momentStratholme"]="Stratholme shall be cleared from Scourge and Scarlet filth alike.|n|nDo you sometimes envy those slain by Arthas here? When he was capable of granting swift death..."
	text["UndeadZoneSilverpine Forest"]="These were lands of Gilneas once. But Gilnean now hide behind the Wall - both from the Scourge and from worgens they're rumored to have foolishly summoned themselves.|n|nLittle presence of the living makes Silverpine a perfect place for our settlements."
	text["UndeadZoneAlterac Mountains"]="City of Dalaran was the last to fall to the Scourge, before demons of the Burning Legion lead most of it across the Sea. Its ruins are covered with magical barrier now, with filthy humans sneaking around."
	text["UndeadZoneLast living momentDalaran"]="You died here, right? It means you almost avoided the undeath. But almost doesn't count."


	text["UndeadFormerRace"]="Rise, my "..Lorehelper_VarFrame.class.."s! Rise, and fight once more!|n|nWhat made you think I've been talking to you?|n|nWhat made you think I am going to ask questions about you? The only relevant event of your past is that you, apparently, died, and was risen in undeath to serve the Lich King. Now, thanks to the Dark Lady, your will is free again. What else to discuss?|n|nOn a more careful thought, however, I am slightly curious. Were you a human or elf when you were alive?"	
	text["UndeadFormerRaceHuman"]="So you're a human, like most of us.|n|nThe Plague has ravaged human kingdom of Lordaeron. The Plague has made us what we are.|n|nArthas, prince of Lordaeron, betrayed his kingdom to become a death knight. It was a nail in the coffin for the kingdom. Or, shall I say, it teared the nails off the coffins so the dead can rise and fight..?"	
	text["UndeadFormerRaceElf"]="So you're an elf, huh? I don't see your pointy ears! Oh well, guess they've rotten off.|n|nArthas, traitor prince of Lordaeron, then a death knight, ravaged elven kingdom of Quel'Thalas. Tainted your precious Sunwell, risen you to serve him. Not necessarily in this order."	

	text["UndeadLastLivingMoment"]="So where exactly did you die?"
	text["UndeadLastMomentBrill"]="Arthas, prince of Lordaeron, came to Brill to investigate the rumors of a plague. The rumors were true.|n|nVillagers of Brill were one of the first victims of the Plague. Here it began, and here it continues - in a sense that you're in a close proximity of Brill right now. Large village of Forsaken it is..."
	text["UndeadLastMomentAndorhal"]="\"One of the largest cities in northern Lordaeron, Andorhal is the main agricultural distribution point in the region.\" Funny to read old brochures sometimes...|n|nKel'Thuzad and his Cult of the Damned infected the grain in Andorhal, for the Plague to spread all across the kingdom. Kel'Thuzad was slain by Arthas the paladin in Andorhal - only to be reanimated by Arthas the death knight few months later."
	text["UndeadLastMomentHearthglen"]="Hearthglen was a target of the Scourge in the beginning of Third War. Some of the citizens - including you, presumably - were unlucky enough to eat some bread, baked from grain from Andorhal. Little did they know of grain being infected by the Plague... Memories get blurry from here, huh?|n|nHearthglen did actually not fall to the Scourge to this day. But I would advice against a nostalgic trip. Zealots of the Scarlet Crusade inhabit the city now. They'll catch you, tortue you, make you regret that you can't die for the second time...|n|nOr maybe you can, if they try hard enough. Willing to test?"
	text["UndeadLastMomentStratholme"]="Stratholme was the second largest city within the kingdom of Lordaeron, matched only by the capital. But the Plague sweeping over Lordaeron reached Stratholme in infected shipments of grain from Andorhal. The citizens - including you, presumably - baked and consumed the infected grain, unknowingly sealing their fates.|n|nBut then the savior came! Thousands avoided the undeath - because prince Arthas massacred them before the Plague could work.|n|nWhat a story. Right now, Stratholme can probably be called the capital of the Scourge."
	text["UndeadLastMomentLordaeronPriest"]="You are from the capital? Is it as beautiful as its said to be? Many people travel to the city seeking wisdom, enlightenment, or cures for their ailments. I am sure the Light helped you to cure hundreds, Priest!|n|nAll these nice streets with blood spilled all over... When prince Arthas killed his father, the city fell into turmoil. At Arthas' command, Falric and Marwyn - once respected army captains, now death knights - led the undead Scourge into the city and killed its inhabitants.|n|nWhen the Lich King's over our minds began to weaken, we, Forsaken, claimed the capital and its surroundings to ourselves. Not sure if your old house is in good condition though."
	text["UndeadLastMomentLordaeronNonPriest"]="You are from the capital? Is it as beautiful as its said to be? Lordaeron is a home to deeply religious ascetics who believed in the Light. Many people travel to the city seeking wisdom, enlightenment, or cures for their ailments.|n|nAll these nice streets with blood spilled all over... When prince Arthas killed his father, the city fell into turmoil. At Arthas' command, Falric and Marwyn - once respected army captains, now death knights - led the undead Scourge into the city and killed its inhabitants.|n|nWhen the Lich King's over our minds began to weaken, we, Forsaken, destroyed the demons who were overseeing the city, and claimed the capital and its surroundings to ourselves. Not sure if your old house is in good condition though."
	text["UndeadLastMomentVandermar"]="Vandermar village, one of the first villages attacked by Arthas the death knight himself. I heard you had quite a few cultists there. Must feel odd to have a chap betraying his fellow villagers into hands of the Scourge.|n|nYou can't find even ruins of your village now. I suppose it was burnt to the ground."
	text["UndeadLastMomentQuelThalasElf"]="You elves and your kingdom of Quel'Thalas stood strong for thousands of years. But Arthas needed to resurrect the necromancer Kel'Thuzad, and the mystic Sunwell, the source of your magic, was the perfect place for it.|n|nThe armies of the Scourge pressed on, breaking through the capital city of Silvermoon. This is where Ranger General Sylvanas Windrunner fell in battle. In a cruel gesture of dominance, Arthas took Sylvanas' lifeless body and ripped her spirit from it, creating the first banshee.|n|nSylvanas is the Banshee Queen now, our cherished Dark Lady. In case your brains have rotten enough for you to need this reminder."
	text["UndeadLastMomentQuelThalasHuman"]="Ancient high elven kingdom of Quel'Thalas stood strong for thousands of years. But Arthas needed to resurrect the necromancer Kel'Thuzad, and the mystic Sunwell, the source of the elves' magic, was the perfect place for it.|n|nThe armies of the Scourge pressed on, breaking through the capital city of Silvermoon. This is where Ranger General Sylvanas Windrunner fell in battle. In a cruel gesture of dominance, Arthas took Sylvanas' lifeless body and ripped her spirit from it, creating the first banshee.|n|nSylvanas is the Banshee Queen now, our cherished Dark Lady. In case your brains have rotten enough for you to need this reminder."
	text["UndeadLastMomentDalaranMage"]="The magocratic city of Dalaran could've in theory been untouched by the Scourge. But you Mages know how to attract trouble.|n|nThe Kirin Tor, your rulers, possessed the Book of Medivh, an artifact that Kel'Thuzad needed to summon Archimonde the Defiler, one of the most powerful demons of Burning Legion. The demonic invasion was, after all, the reason why the Lich King, Plague, and the Scourge were created in the first place.|n|nSo the Book was acquired, Archimonde summoned, the city destroyed, and some of its protectors - including you - risen in the undeath."	
	text["UndeadLastMomentDalaranNonMage"]="The magocratic city of Dalaran could've in theory been untouched by the Scourge. But the Kirin Tor, its rulers, possessed the Book of Medivh, an artifact that Kel'Thuzad needed to summon Archimonde the Defiler, one of the most powerful demons of Burning Legion. The demonic invasion was, after all, the reason why the Lich King, Plague, and the Scourge were created in the first place.|n|nSo the Book was acquired, Archimonde summoned, the city destroyed, and some of its protectors - including you - risen in the undeath."	

	text["UndeadEventDreadlordsFall"]="Shortly after the Scourge annihilated the last of the civilian presence in Lordaeron, the Lich King began to lose control of the minds of Sylvanas and a number of banshees. Soon, Arthas left for Northrend, having been summoned by the Lich King, and Kel'Thuzad went into hiding.|n|nBut the plagued lands of Lordaeron were under control of the demonic dreadlords. Many of us freed from the Lich King only to have our minds immediately possessed by them.|n|nSo Sylvanas began the fight for her freedom - and for freedom of us all. The Dark Lady found a plethora of creatures who would serve her well, and with her banshees at her disposal, they would have little choice in the matter."
	text["UndeadEventDreadlordsFallStandard"]="There were three of the dreadlords. Varimathras have betrayed his brothers and joined forces with Sylvanas. Detheroc and Balnazzar, as well as their human puppet, Garithos, were all slain by our cunning Queen."
	------------------------------------------------------------
	------------------------------------------------------------
	------------------------------------------------------------
	text["OrcClan"]="In the New Horde, most clan separations have disintegrated. We all fight for our Warchief as equal.|n|nAnd yet, your clan often matters. An honorable clan are orcs whose example inspire you, these are orcs you want to be proud of you.|n|nWhat is your clan of birth?"
	text["OrcClanBlackrock"]="At different times, Blackrock clan meant a great treachery and  a great glory. It was the ego of your leader, Blackhand the Destroyer, that allowed Gul'dan to corrupt our race. Later, however, our great Warchief Orgrim Doomhammer seized the power from that puppet of warlocks.|n|nThese days, leaders of the dark Horde call themselves Blackrocks. They remained steadfast to the \"ideals\" of the old Horde, including demon worship and depraved bloodlust. Rumors are, they are still slaves, not to demons but to another force that resides on top of Blackrock Spire.|n|nI am happy to see a Blackrock loyal to the New Horde. One day, dark Horde will be no more, and Thrall will lead all orcs to the greater future."
	text["OrcClanBleedingHollow"]="Bleeding Hollow clan is one of the most legendary ones. Your chieftain, Kilrogg Deadeye, lead the clan from earlier days of cowering from the arakkoa in the depths of the Tanaan Jungle, to eventual victory over the arakkoa and many more victories thereafter.|n|nThe clan fought with honor against humans in Azeroth. When Draenor, our home world, started to collapse, many of you managed to escape - only to be captured by humans.|n|nYears of imprisonment followed, but now, thanks to our great Warchief Thrall, we are liberated."
	text["OrcClanBurningBladeWarlock"]="Not so much a clan as a vast asylum, the Burning Blade consisted of the best swordsmen of the Horde - and the most bloodlusty ones. So uncontrollable that they were only released to fight once during Second War - when Alliance laid siege to Blackrock Spire.|n|nI don't think you were one of them. Only a couple dozens survived the battle, and they all are famous Blademasters.|n|nI think you are a former member of the newfound Burning Blade. The cult that opposes the New Horde and seeks to bring us back to the age of demonic slavery and bloodlust.|n|nI keep an eye on you, Warlock. You better slay the Burning Blade scum on sight to prove your loyalty to Warchief."
	text["OrcClanBurningBladeNonWarlock"]="Not so much a clan as a vast asylum, the Burning Blade consisted of the best swordsmen of the Horde - and the most bloodlusty ones. So uncontrollable that they were only released to fight once during Second War - when Alliance laid siege to Blackrock Spire.|n|nI don't think you were one of them. Only a couple dozens survived the battle, and they all are famous Blademasters.|n|nI think you are a former member of the newfound Burning Blade. The cult that opposes the New Horde and seeks to bring us back to the age of demonic slavery and bloodlust.|n|nYour past does not matter, as long as you prove your loyalty to Warchief - in particular, by slaying the Burning Blade scum!"
	text["OrcClanDragonmaw"]="Thanks to Deathwing the Destroyer, the Dragonmaws found Demon Soul - an artifact of immense power that they used to capture the Dragonqueen Alexstrasza. This is why we had dragons fighting for the Horde in this war.|n|nLater, humans managed to destroy the artifact, and the freed dragons incinerated much of your clan. But some elements remain to this day in Wetlands. These forces are led by Nek'rosh Skullcrusher, who serves the self-styled warchief of the dark Horde, Rend Blackhand.|n|nI am happy to see a Dragonmaw loyal to the New Horde. One day, dark Horde will be no more, and Thrall will lead all orcs to the greater future."
	text["OrcClanFrostwolf"]="I bow to you, Frostwolf. You were one of very few clans not to partake of the demonic blood which corrupted the other clans. For this, Gul'dan, pawn of the demons, declared the Frostwolves to be outlaws.|n|nFearing for the safety of his people, Durotan, father of our Warchief Thrall, led the clan to settle in the distant Alterac Mountains. Shortly thereafter, he and his wife Draka were murdered by assassins on the orders of Gul'dan...|n|nThroughout the Wars in Azeroth the Frostwolves remained in hiding, practicing the old traditions under the leadership of their shaman Drek'Thar. Eventually, Thrall sought them out. Under the tutelage of Drek'Thar, Thrall became a shaman and began a crusade to re-awaken the orcs to our heritage and free us from the demonic corruption that had plagued us for so long.|n|nThe Frostwolves who remain in Alterac now have been caught up in the new battle with the filthy dwarves. Maybe one day you will also fight for your clan's homeland."
	text["OrcClanShatteredHandRogue"]="Your clan was named for an act of sacrifice made by Kargath Bladefist and his fellow orcs that lead to a successful rebellion and freedom from slavery under the ogres.|n|nMost of the Shattered Hand remained on Draenor, our home world, during the Wars in Azeroth. When Draenor started to collapse, many of you managed to escape - only to be captured by humans.|n|nWith the foundation of Durotar, the Shattered Hand has become the Horde's guild of assassins, training new rogues in the service of the Warchief.|n|nEven though you are a rogue of Shattered Hand, I imagine you'll need to earn the respect of your clan just as everyone else does - not by birth, but by your deeds."
	text["OrcClanShatteredHandNonRogue"]="Your clan was named for an act of sacrifice made by Kargath Bladefist and his fellow orcs that lead to a successful rebellion and freedom from slavery under the ogres.|n|nMost of the Shattered Hand remained on Draenor, our home world, during the Wars in Azeroth. When Draenor started to collapse, many of you managed to escape - only to be captured by humans.|n|nWith the foundation of Durotar, the Shattered Hand has become the Horde's guild of assassins, training new rogues in the service of the Warchief."
	text["OrcClanTwilightsHammerWarlock"]="So not only you are a shady Warlock, you are also from Twilight's Hammer. I wonder if I should smash your skull instead of chatting.|n|nTwilight's Hammer has grown to a cult greater than the orcs - and much, much darker. Obsessed with the idea that the Horde was the harbinger of apocalyptic doom to all the lands that it ravages, the clan felt a sacrosanct gratification in the destruction of all that it encountered. Its loyalty to the Horde was not as strong as its belief in its sacred mission of oblivion.|n|nWe would have probably executed all these lunatics if we could conquer the humans first! But we could not. The cult, now extended by all races of Azeroth, serves the Old Gods, seeking to destroy all creation.|n|nYour past does not matter, as long as you prove your loyalty to Warchief - in particular, by slaying the Twilight's Hammer scum!"
	text["OrcClanTwilightsHammerNonWarlock"]="Twilight's Hammer has grown to a cult greater than the orcs - and much, much darker. Obsessed with the idea that the Horde was the harbinger of apocalyptic doom to all the lands that it ravages, the clan felt a sacrosanct gratification in the destruction of all that it encountered. Its loyalty to the Horde was not as strong as its belief in its sacred mission of oblivion.|n|nWe would have probably executed all these lunatics if we could conquer the humans first! But we could not. The cult, now expanded by all races of Azeroth, serves the Old Gods, seeking to destroy all creation.|n|nYour past does not matter, as long as you prove your loyalty to Warchief - in particular, by slaying the Twilight's Hammer scum!"
	text["OrcClanWarsong"]="One of the strongest and most violent, your clan was also one of the most distinguished clans on Draenor. It then fought with honor against humans in Azeroth.|n|nWith the destruction of the Dark Portal the Warsong clan retreated to Stonard, and was forced into hiding in the wilds of Lordaeron. During this time, the chieftain of the clan, Grom Hellscream, was constantly battling the demonic curse that had left us all weakened and listless. Where other orcs gave in to this malaise, Grom fought it to the end of his days.|n|nLater reunited with Orgrim and Thrall, Grom was a hero of Third War as well. The cunning demon Mannoroth managed to corrupt him once more, but with Thrall's help, Grom was able to overcome the bloodlust, and the two faced and killed Mannoroth. This is how Grom freed himself at last - and freed us all.|n|nMany of Warsongs now fight in Ashenvale, where they are defending Horde's logging operations from the pesky elves. Maybe one day you will fight alongside your clan there."
	text["OrcClanMinor"]="Don't be offended over the word \"minor\". It's just, many clans don't exist anymore.|n|nI'd be very surprised to hear that you identify yourself with Shadowmoon, or Bonechewer, or any other clan that perished with Draenor. Or with Stormreaver, most of whom were doomed by the power-lust of Gul'dan, their leader.|n|nBut even without great names in your past, you can make yourself a great future!"
	------------------------------------------------------------
	------------------------------------------------------------
	------------------------------------------------------------
	------------------------------------------------------------
	------------------------------------------------------------
	------------------------------------------------------------
	text["MsgAnswersLoaded"]="Lorehelper: your past answers loaded."
	text["MsgRetakeTest"]="Are you sure you want to do the lore test again? Your old answers will be lost."
	text["MsgAccessLoreProfile"]="Lorehelper: you can access your lore profile via the minimap icon, or by typing /lore"
	text["MsgAboutLH"]="Lorehelper compiles the official lore disclosed by Blizzard, various texts from Wowpedia and WoWWiki, and my own humble efforts into a lore-focused race-specific \"test\". Once you finish it, you will have access to your lore profile.|n|nAdditionally, when you first time enter a zone that is important from the lore standpoint, you will see a popup text about this zone, slightly different depending on your character's backstory. You may also receieve some tips about quests you should not miss.|n|nIn situations when the official lore is uncertain, I tried to come up with the most sensible solution. For example, we do not know when dwarves normally become old, but since Muradin Bronzebeard was 221 years old during the Third War, I came up with a guesstimate of 500 as a \"maximum\" age of a dwarf.|n|nI sincerely apologise to those who wanted to RP a 501-years-old dwarf, as well as to anyone who find the \"test\" limiting.|n|nHuge thanks to Wowpedia and WoWWiki authors for immensive efforts on lore collection. And, of course, to Blizzard for creating this wonderful World!|n|nYours,|nNimeral"
	--Another example is, it is unclear when Darkspear trolls were driven from Stranglethorn, the addon supposes it is after the Second War when an ogre-mage was more likely to roam around Azeroth, seeking a troll tribe to seize their land.
	------------------------------------------------------------	
	------------------------------------------------------------
	------------------------------------------------------------
	------------------------------------------------------------
	------------------------------------------------------------
	------------------------------------------------------------
	------------------------------------------------------------
	------------------------------------------------------------
	------------------------------------------------------------
	------------------------------------------------------------
end
